CREATE TABLE SEQUENCES (
  SEQ_NAME VARCHAR(22) NOT NULL,
  SEQ_VALUE INT UNSIGNED NOT NULL,
  PRIMARY KEY SEQ_NAME
);

CREATE TABLE ENVIRONMENT (
	ID INTEGER NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	COMMENT VARCHAR(500) NULL,
	STATUS INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE APPLICATION (
	ID INTEGER NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	COMMENT VARCHAR(500) NULL,
	STATUS INTEGER NOT NULL,
	PRIMARY KEY (ID)
);
